### ISSUE TITLE
Module AppRegistry is not a registered callable module

### ISSUE THREAD

**Issue by stickperson** [jhabdas/react-native-webpack-starter-kit#67] opened 2016-03-11 20:38 UTC
I'm getting the following error while testing the app on android: `Module AppRegistry is not a registered callable module`. I cloned the repo, ran `npm install`, started running my android emulator and then ran `npm start` followed by `npm run android-setup-port` and `react-native run-android` in a separate window.

The app loads but I'm greeted by a red screen with the message. I went through the React Native documentation and got their sample android project up and running, so that's not the issue.

**Comment by jhabdas** [comment] 2016-03-11 20:39
Duplicate of https://github.com/jhabdas/react-native-webpack-starter-kit/issues/58

**Comment by jhabdas** [comment] 2016-03-11 20:40
@stickperson I'm working to restore Android functionality. Feel free to drop anything you learn into the related issue.

**Closed by jhabdas** 2016-03-11 20:39 UTC

**Comment by stickperson** [comment] 2016-03-11 20:41
@jhabdas will do. Sorry for the duplicate.

**Comment by jhabdas** [comment] 2016-03-11 20:42
@stickperson I just updated the title of the other issue. Yours was much more descriptive.
