### ISSUE TITLE
[Android] undefined is not an object (evaluating ReactPerf().injection.injectMeasure)

### ISSUE THREAD

**Issue by boulajp** [jhabdas/react-native-webpack-starter-kit#101] opened 2016-05-21 19:58 UTC
This is an error that I see when trying to load an app onto my phone.

Device info:
Nexus 6p
Android 6.0.1

**Comment by jhabdas** [comment] 2016-05-22 15:46
@boulajp Unfortunately that's not enough information to debug. Please provide full recreation steps and include your current kit version, node and npm version when reopening. Thanks!

**Comment by almeidarruben** [comment] 2016-05-25 00:09
Hi,
I'm experiencing the same issue. 

Everything was working fine until I update the following packages: 
- `react` from `0.14.8` to `15.1.0`
- `react-native` from `0.24` to `0.26.1` or `0.26.2`

If I remove my node modules I roll back to the previous versions, everything works again.

**Comment by DarrylD** [comment] 2016-05-28 18:54
Having the same issue
npm - 3.9.2
node - 5.5.0
webpack - 1.13.1

Here is the error 
![screen shot 2016-05-28 at 2 52 59 pm](https://cloud.githubusercontent.com/assets/1310383/15629311/eff0bb6e-24e3-11e6-96f2-2d11b02badb1.png)

**Comment by jhabdas** [comment] 2016-05-28 19:10
Thanks for the info. When I made the `0.26` update for the kit I tried out [`rnpm`](https://github.com/rnpm/rnpm) (as described in the [release notes](https://github.com/jhabdas/react-native-webpack-starter-kit/releases)) to do the update. Looks like it didn't work out so hot.

Until I have a chance to roll back and get my test environment set-up you can roll back to RN `0.25` by doing a `rm -rf node_modules && git checkout tags/v2.25.2 && npm i` from the project root.

@DarrylD I'm on a fresh laptop. Could you give the rollback steps above a shot and let me know if it clears up your issue?

**Comment by DarrylD** [comment] 2016-05-28 19:54
Thx for the fast response!

Are the above steps correct? Fairly new to RN.

New error:
![error2](https://cloud.githubusercontent.com/assets/1310383/15629639/6d43649c-24ec-11e6-8bc6-0110c51434d4.png)

**Comment by jhabdas** [comment] 2016-05-28 19:56
No problem. I'm here to help. Are you trying to run on a simulator?

**Comment by DarrylD** [comment] 2016-05-28 20:01
I am.

**Comment by jhabdas** [comment] 2016-05-28 20:26
Thanks for the info @DarrylD. This bug's a dupe of https://github.com/jhabdas/react-native-webpack-starter-kit/issues/58. Perhaps you could give http://getpepperoni.com/ a try and let me know how it works for you?

**Comment by weixingsun** [comment] 2016-06-10 13:31
@jhabdas I don't think this is duplicate to #58. 
I am on a real device and RN 0.26.3 , sometimes, roll back to RN 0.25 is not reasonable for a product. 
Would you mind to re-open it? and do you got an idea to fix it?

**Comment by jhabdas** [comment] 2016-06-10 16:02
Reopened. To be clear this is a project not a product.

**Comment by Abdenasser** [comment] 2016-06-10 17:03
i spent last night trying to figure out what's happening, unfortunately i found **nothing** 
![screenshot_2016-06-10-01-06-16](https://cloud.githubusercontent.com/assets/8364240/15972289/1602b4bc-2f2d-11e6-939b-ccff81c831ea.png)

**Comment by jhabdas** [comment] 2016-06-10 17:11
Anyone know how Pepperoni is working for Android? http://habd.as/awesome-react-boilerplates/#react-native

**Comment by weixingsun** [comment] 2016-06-11 01:05
Hi @jhabdas 
I had solved this problem by using consistent version of react(15.0.2) and react-native(0.26.3)
Looks like this is an env configuration problem, and I was using react (15.1.0) , there are many other guys who were annoying about it. 
Thanks for help, it should not an issue with webpack-starter-kit.

**Comment by jhabdas** [comment] 2016-06-21 14:13
Thanks for the info @weixingsun. This was addressed in package manifest a while ago by pinning the react minor to the `15.0` range after I noticed the `15.1` release causing problems.

**Closed by jhabdas** 2016-06-21 14:13 UTC
