### ISSUE TITLE
Babel error on npm start

### ISSUE THREAD

**Issue by Ehesp** [jhabdas/react-native-webpack-starter-kit#11] opened 2015-11-05 10:24 UTC
After running `npm install`, then running `npm start` I get the following error:

```
> App@0.0.1 start /react-native-app
> rnws start

/react-native-app/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^

ReferenceError: [BABEL] /react-native-app/node_modules/react-native/packager/react-packager/src/Activity/index.js: Unknown option: /react-native-app/node_modules/react-native/packager/react-packager/.babelrc.whitelist
    at Logger.error (/react-native-app/node_modules/babel-core/lib/transformation/file/logger.js:43:11)
    at OptionManager.mergeOptions (/react-native-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:245:18)
    at OptionManager.addConfig (/react-native-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:206:10)
    at OptionManager.findConfigs (/react-native-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:347:16)
    at OptionManager.init (/react-native-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:392:12)
    at File.initOptions (/react-native-app/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/react-native-app/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/react-native-app/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at Object.transformFileSync (/react-native-app/node_modules/babel-core/lib/api/node.js:113:10)
    at compile (/react-native-app/node_modules/babel-core/lib/api/register/node.js:111:20)
    at loader (/react-native-app/node_modules/babel-core/lib/api/register/node.js:136:14)
    at Object.require.extensions.(anonymous function) [as .js] (/react-native-app/node_modules/babel-core/lib/api/register/node.js:146:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/nsolid" "/usr/local/bin/npm" "start"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE
npm ERR! App@0.0.1 start: `rnws start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the App@0.0.1 start script 'rnws start'.
```

Node 5.0.0
NPM 3.3.9

**Comment by jhabdas** [comment] 2015-11-05 10:34
Whoops! Thanks for the report. That started when I bumped Babel to v6. But it's happening for me too now that I've blown away my `node_modules`. Please feel free to revert to the last versioned release for the time being.

**Comment by jhabdas** [comment] 2015-11-05 10:39
Here's a possibly related issue: https://github.com/mjohnston/react-native-webpack-server/issues/121

**Comment by Ehesp** [comment] 2015-11-05 10:45
I've reverted back, the build works but I'm now getting the error on Android load:

![image](https://cloud.githubusercontent.com/assets/842078/10966266/5db54a6a-83aa-11e5-8979-e7e3f4943656.png)

**Comment by jhabdas** [comment] 2015-11-05 10:47
That RedBox error doesn't say a whole lot on its own. What did you revert back to, exactly?

**Comment by Ehesp** [comment] 2015-11-05 10:48
I reverted the changes in this commit:

https://github.com/jhabdas/react-native-webpack-starter-kit/commit/0622316047825bafdd8bbd219d8fe3f4e75f4e12

**Comment by jhabdas** [comment] 2015-11-05 11:00
Yeah, bummer. I did a `git reset --hard v1.13.2` and got the same. Looks like something's borked in `react-native-webpack-server` following the update to `react-native@^0.13.0` and NPM 3. It'll take some more digging.

**Comment by Ehesp** [comment] 2015-11-05 11:40
Cheers - let me know how you get on, will do some digging myself.

**Comment by manuelmazzuola** [comment] 2015-11-05 17:17
Any updates ?

**Comment by jhabdas** [comment] 2015-11-05 17:49
Not yet. Taking a look now. @manuelmazzuola are you building iOS or Android?

**Comment by jhabdas** [comment] 2015-11-05 19:06
Resoled with https://github.com/jhabdas/react-native-webpack-starter-kit/releases/tag/v1.13.5. The changes required were minimal. Please set project as your upstream branch and merge the corresponding tag to your project to resolve the issue. Thanks again.

**Comment by jhabdas** [comment] 2015-11-05 19:11
I lied. Use [v0.13.6](https://github.com/jhabdas/react-native-webpack-starter-kit/releases/tag/v0.13.6).

**Comment by Ehesp** [comment] 2015-11-05 20:14
@jhabdas Unfortunately getting the same problem. Also with the changes it pulled Babel 6 back in (which threw the original error). Reverted back to 5, and now I'm still getting the "App has not been registered" error.

Also tried a fresh pull of the repo, following the installation instructions.

**Comment by jhabdas** [comment] 2015-11-06 00:12
@Ehesp Based on some research this morning I discovered this issue isn't a result of the Babel 6 upgrade, so that code stays and you'll see it in newer versions. What I didn't realize in closing this issue is that fresh clones were still busted. I'm going to update the `README`, but here's the workaround:

```sh
npm install
npm un -D react-native-webpack-server && npm i -D react-native-webpack-server
npm start
```

Seems to me this may be an issue with NPM 3, so I'm hoping whatever the issue is will get resolved in time. If that doesn't work for you please reopen this issue. Thanks!

**Comment by Ehesp** [comment] 2015-11-06 08:40
Unfortunately that didn't work :(

Same issue/error message. Also I tried to build for iOS (no knowledge of iOS dev at all) and it's got the following error:

![image](https://cloud.githubusercontent.com/assets/842078/10992861/0f43a21a-8462-11e5-9763-cb516418d9a7.png)

**Comment by jhabdas** [comment] 2015-11-06 14:43
That's strange. I'm reopening the issue for debugging purposes. To try and reproduce your issue more closely I did an `nvm install v5.0.0 && npm install -g npm@3.3.9` and then followed the updated install instructions from the README (including the workaround) and, once the workaround was applied, didn't have any issues running the app or starting it in the iOS simulator.

@Ehesp could you try the following with a fresh install one more time and let me know how it goes:

```
git clone https://github.com/jhabdas/react-native-webpack-starter-kit.git kit && cd $_
npm install
npm un -D react-native-webpack-server && npm i -D react-native-webpack-server
npm start
```

**Comment by Ehesp** [comment] 2015-11-06 15:23
Okay followed the instructions to the letter.

Works on iOS, but not Android (with the same error).

![image](https://cloud.githubusercontent.com/assets/842078/11000548/58e070c8-849a-11e5-8deb-c9688adea8ea.png)

**Comment by jhabdas** [comment] 2015-11-06 15:30
Excellent. Please feel free to open a separate issue for Android, thought it's likely someone else will do it (or just fix it with a PR in time). A lot of stuff is moving in the React Native and Node spaces right now so I'm going to let this one sit on the back burner to see if it doesn't get cleared up with the upgrade to RN `0.14`. Thanks for your persistence!

**Closed by jhabdas** 2015-11-06 15:30 UTC
